### PR TITLE
🚀 Created some little banners

### PR DESCRIPTION
**Pull request by lucemans**
"Thought was cute, might delete later 📷"

Shows this in the console,
image

And this ontop of all the html
image

### CODE REVIEW

**Comment by lucemans** [comment]
Also, unrelated 👀, but im digging the dark vibe

image

**Comment by w3cj** [comment]
This is great! A few requests though:

1. Specify each style on a new line so its a bit easier to read
2. Use `vw` for widths instead of `rem` I have a very zoomed in console and things are chopped off, but with `vw` it resizes nicely.

This seemed to work nicely:

```js
      console.log(
        "%c ENTROPY%cCHAT \n%c       Created by the %cCoding Garden Community%c       \n                                                    ",
        "color: #fff; font-size: 6vw; background: #290016",
        "color: #dc136c; font-size: 6vw; background: #290016",
        "color: #fff; font-size: 1.5vw; background: #290016",
        "color: #dc136c; text-decoration: underline; font-size: 1.5vw; background: #290016",
        "font-size: 1.5vw; background: #290016"
      );
```

**Review by w3cj — CHANGES_REQUESTED** [review]
See comments above.

**Comment by lucemans** [comment]
image
This is what it looks like on my machine, dont know if that is preferred or not...

**Comment by nmigueles** [comment]
This is how it looks on my console with the VH units. (Chrome)

Captura

LGTM

**Review by w3cj — APPROVED** [review]
Looks great!

**Pull request merged**
